# Load data

In [1]:
# Import pandas
import pandas as pd

## Custom `read_tsv()` Function

We define a custom `read_tsv()` function based on pandas `read_csv()` method to properly load tab separated (TSV) files.

The raw data files do not include header rows, so using `read_csv()` directly would result in unnamed columns. To address this, we specify the column names when loading the data.

In [2]:
# Define function to read in tsv file with correct columns
def read_tsv(file_path, columns):
    """
    Read a tab-separated (TSV) file into a pandas DataFrame
    using a user-provided list of column names.

    Parameters
    -----------
        file_path : str
            Path to the TSV file.
        columns : list
            Column names to assign to the DataFrame.

    Returns
    --------
        pandas.DataFrame
            DataFrame containing the loaded TSV data
            with the specified column names.
    """
    return pd.read_csv(
        file_path,
        sep= "\t",
        header= None,
        names = columns
    )

In [3]:
# Initialize list of movie, character, and plot columns
movie_metadata_cols = [
    "wiki_movie_id",
    "freebase_movie_id",
    "movie_name",
    "release_date",
    "bo_revenue",
    "runtime",
    "languages",
    "countries",
    "genres"
]

character_metadata_cols = [
    "wiki_movie_id",
    "freebase_movie_id",
    "movie_release_date",
    "character_name",
    "actor_dob",
    "actor_gender",
    "actor_height",
    "actor_ethnicity",
    "actor_name",
    "actor_age_at_release",
    "freebase_character_map",
    "freebase_character_id",
    "freebase_actor_id"
]

plot_cols = [
    "wiki_movie_id",
    "plot"
]

In [4]:
# Call function on 3 different files
movies = read_tsv("movie.metadata.tsv", movie_metadata_cols)
characters = read_tsv("character.metadata.tsv", character_metadata_cols)
movie_plots = read_tsv("plot_summaries.txt", plot_cols)

In [5]:
# View all columns
dataframes = [movies, characters, movie_plots]
for df in dataframes:
    display(df.head())

,wiki_movie_id,freebase_movie_id,movie_name,release_date,bo_revenue,runtime,languages,countries,genres
0,975900,/m/03vyhn,Ghosts of Mars,2001-08-24,14010832.0,98.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/01jfsb"": ""Thriller"", ""/m/06n90"": ""Science..."
1,3196793,/m/08yl5d,Getting Away with Murder: The JonBenét Ramsey ...,2000-02-16,NaN,95.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/02n4kr"": ""Mystery"", ""/m/03bxz7"": ""Biograp..."
2,28463795,/m/0crgdbh,Brun bitter,1988,NaN,83.0,"{""/m/05f_3"": ""Norwegian Language""}","{""/m/05b4w"": ""Norway""}","{""/m/0lsxr"": ""Crime Fiction"", ""/m/07s9rl0"": ""D..."
3,9363483,/m/0285_cd,White Of The Eye,1987,NaN,110.0,"{""/m/02h40lc"": ""English Language""}","{""/m/07ssc"": ""United Kingdom""}","{""/m/01jfsb"": ""Thriller"", ""/m/0glj9q"": ""Erotic..."
4,261236,/m/01mrr1,A Woman in Flames,1983,NaN,106.0,"{""/m/04306rv"": ""German Language""}","{""/m/0345h"": ""Germany""}","{""/m/07s9rl0"": ""Drama""}"

,wiki_movie_id,freebase_movie_id,movie_release_date,character_name,actor_dob,actor_gender,actor_height,actor_ethnicity,actor_name,actor_age_at_release,freebase_character_map,freebase_character_id,freebase_actor_id
0,975900,/m/03vyhn,2001-08-24,Akooshay,1958-08-26,F,1.620,NaN,Wanda De Jesus,42.0,/m/0bgchxw,/m/0bgcj3x,/m/03wcfv7
1,975900,/m/03vyhn,2001-08-24,Lieutenant Melanie Ballard,1974-08-15,F,1.780,/m/044038p,Natasha Henstridge,27.0,/m/0jys3m,/m/0bgchn4,/m/0346l4
2,975900,/m/03vyhn,2001-08-24,Desolation Williams,1969-06-15,M,1.727,/m/0x67,Ice Cube,32.0,/m/0jys3g,/m/0bgchn_,/m/01vw26l
3,975900,/m/03vyhn,2001-08-24,Sgt Jericho Butler,1967-09-12,M,1.750,NaN,Jason Statham,33.0,/m/02vchl6,/m/0bgchnq,/m/034hyc
4,975900,/m/03vyhn,2001-08-24,Bashira Kincaid,1977-09-25,F,1.650,NaN,Clea DuVall,23.0,/m/02vbb3r,/m/0bgchp9,/m/01y9xg

   wiki_movie_id                                               plot
0       23890098  Shlykov, a hard-working taxi driver and Lyosha...
1       31186339  The nation of Panem consists of a wealthy Capi...
2       20663735  Poovalli Induchoodan  is sentenced for six yea...
3        2231378  The Lemon Drop Kid , a New York City swindler,...
4         595909  Seventh-day Adventist Church pastor Michael Ch...

# Transform Data

### Custom `get_dict_values()` Function

We defined a custom `get_dict_values()` function to extract and format the values stored in specific text columns.

Some columns in the ``movies`` dataset such as `language`, `countries`, and `genres` contain dictionary data stored as strings. The function converts each string into a dictionary using `ast.literal_eval()`, then extracts the dictionary values and joins them into a single comma-separated string.

**Reference:**
- https://www.geeksforgeeks.org/python/ways-to-convert-string-to-dictionary/

In [6]:
# Define function to get values from dictionary
import ast
def get_dict_values(col):
    """
        Convert a dictionary-like string into a comma-separated string of its values.
        
        Parameters
        ----------
            col : str 
                A dictionary-like string or missing value.

        Returns
        -------
            str
                A comma-separated string of dictionary values, or an empty string
                if the input is missing.
        """
    # Check that the column isn't missing values
    if pd.isna(col):
        return ""
    else:
        # Otherwise return the formated string
        dictionary = ast.literal_eval(col)
        return ", ".join(dictionary.values())

In [7]:
# Call on movies
movies['languages'] = movies['languages'].apply(get_dict_values)
movies['countries'] = movies['countries'].apply(get_dict_values)
movies['genres'] = movies['genres'].apply(get_dict_values)

In [8]:
# Remove "Language" from languages column in movies dataframe
movies['languages'] = movies['languages'].str.replace("Language", "")

In [9]:
# View result
movies.head()

,wiki_movie_id,freebase_movie_id,movie_name,release_date,bo_revenue,runtime,languages,countries,genres
0,975900,/m/03vyhn,Ghosts of Mars,2001-08-24,14010832.0,98.0,English,United States of America,"Thriller, Science Fiction, Horror, Adventure, ..."
1,3196793,/m/08yl5d,Getting Away with Murder: The JonBenét Ramsey ...,2000-02-16,NaN,95.0,English,United States of America,"Mystery, Biographical film, Drama, Crime Drama"
2,28463795,/m/0crgdbh,Brun bitter,1988,NaN,83.0,Norwegian,Norway,"Crime Fiction, Drama"
3,9363483,/m/0285_cd,White Of The Eye,1987,NaN,110.0,English,United Kingdom,"Thriller, Erotic thriller, Psychological thriller"
4,261236,/m/01mrr1,A Woman in Flames,1983,NaN,106.0,German,Germany,Drama

## Creating a Cast Dataset

We create a smaller copy of the `characters` dataframe that keeps only the most relevant fields for the RAG pipeline: `wiki_movie_id`, `character_name`, and `actor_name`. We wanted to include only information needed to connet movies to their characters and actors.

In [ ]:
# Create a copy of the character dataframe and subset
characters_small = characters[['wiki_movie_id', "character_name", "actor_name"]].copy()

# Basic cleaning (removing leading and lagging whitespaces)
for col in ['character_name', "actor_name"]:
    characters_small[col] = characters_small[col].str.strip()

Below we create character actor paris by using string concatenation. It follows the format: ``character: actor``

Example:
``Katniss Everdeen: Jennifer Lawrence``

In [11]:
# Replace missing data
characters_small['actor_name'] = characters_small['actor_name'].fillna("Unknown Actor")
characters_small['character_name'] = characters_small['character_name'].fillna("Unknown Character")

# Create character_actor column
characters_small['character_actor'] = characters_small['character_name'] + ": " + characters_small['actor_name']

In [12]:
# View result
characters_small[characters_small['character_name'].str.contains("Katniss Ever")]

,wiki_movie_id,character_name,actor_name,character_actor
363229,31186339,Katniss Everdeen,Jennifer Lawrence,Katniss Everdeen: Jennifer Lawrence

## Aggregating Cast Information by Movie

At this stage, the character-actor data still contains multiple rows per movie, with each row representing a single character and actor pair. To prepare the data for retrieval, we aggregate this information so that each movie has only one row.

We group the data by `wiki_movie_id` and collect all `character_actor` entries for the same movie into a list using `apply(list)`. This creates a single record per movie while preserving all associated character-actor pairs.

Afterwards `reset_index()` converts the grouped result back into a pandas dataframe.

In [13]:
# Aggregate to one row per movie
characters_agg = characters_small.groupby('wiki_movie_id')['character_actor'].apply(list).reset_index()

# View result
print(characters_agg.iloc[3]['character_actor'][:5])

# Print a couple rows
characters_agg.head()

['J.F. Sebastian: William Sanderson', 'Rick Deckard: Harrison Ford', 'Roy Batty: Rutger Hauer', 'Rachael: Sean Young', 'Pris: Daryl Hannah']

   wiki_movie_id                                    character_actor
0            330  [Unknown Character: Rosa Maria Sardà, Unknown ...
1           3217  [S-Mart Clerk: Ted Raimi, Fake shemp: Ivan Rai...
2           3333  [Unknown Character: Lillian Gish, Unknown Char...
3           3746  [J.F. Sebastian: William Sanderson, Rick Decka...
4           3837  [Gabby Johnson: Jack Starrett, Taggart: Slim P...

## Reformatting Cast Entries

After aggregation, each movie contains a list of `character_actor` strings. However, some characters may appear more than once if multiple actors are associated with the same role.

To make this information cleaner and easier to read, we define a custom `reformat_character_actor()` function, it creates a dictionary in which each key is the character and the values are the actors who played that character. 

Overall this a more readable cast representation and creates cleaner text for cast-based chunks. This is the dataset we'll later use for merging.

In [ ]:
# Create function to reformat character_actor
def reformat_character_actor(character_actor):
    """
    Reformat a list of character-actor strings into a structured multiline string.

    This function takes a list of strings in the format `character:actor`,
    groups actors by character name, and returns a cleaner text representation
    where each character appears once followed by its associated actor or actors.

    Parameters
    ----------
        character_actor : list
            List of character-actor strings.

    Returns
    --------
        str
            Multiline string where each line contains a character name
            followed by one or more associated actor names.
    """
    # Initialie dictionary to hold character-actor 
    character_dict = {}

    # Split each "character:actor" entry and group actors under each character
    for i in character_actor:
        parts = i.split(":")
        character = parts[0]
        actor = parts[1]

        # Populate dictionary keys
        if character not in character_dict:
            character_dict[character] = []
        
        # Add values to the dictionary
        character_dict[character].append(actor)

    # Initialize list to store clean strings
    clean_format = []

    # Rebuild the grouped data into a readable "character: actor1, actor2" format
    for character, actor in character_dict.items():
        clean_format.append(f"{character}: {', '.join(actor)}")

    # Return one multiline string per movie
    return "\n".join(clean_format)

# Apply formatting function to aggregated character-actor column
characters_agg['character_actor'] = characters_agg['character_actor'].apply(reformat_character_actor)

In [15]:
# View result
print(characters_agg.iloc[4]['character_actor'])
characters_agg.head()

Gabby Johnson:  Jack Starrett
Taggart:  Slim Pickens
Unknown Character:  Dave Sharpe,  Count Basie,  Don Megowan,  Charles McGregor
Rev. Johnson:  Liam Dunn
Mongo:  Alex Karras
Buddy Bizarre:  Dom DeLuise
Olson Johnson:  David Huddleston
Lyle:  Burton Gilliam
Governor WIlliam J. Lepetomane:  Mel Brooks
Lili Von Shtupp:  Madeline Kahn
Howard Johnson:  John Hillerman
Hedley Lamarr:  Harvey Korman
Jim:  Gene Wilder
Bart:  Cleavon Little
Harriett Johnson:  Carol Arthur
Dr. Sam Johnson:  Richard Collier
Van Johnson:  George Furth

   wiki_movie_id                                    character_actor
0            330  Unknown Character:  Rosa Maria Sardà,  Mercè P...
1           3217  S-Mart Clerk:  Ted Raimi\nFake shemp:  Ivan Ra...
2           3333  Unknown Character:  Lillian Gish,  Henry B. Wa...
3           3746  J.F. Sebastian:  William Sanderson\nRick Decka...
4           3837  Gabby Johnson:  Jack Starrett\nTaggart:  Slim ...

# Merge Data

## Merging Plot and Metadata Datasets
To create a more complete movie-level dataset, we merge the plot summary data with the movie metadata using `wiki_movie_id` as the shared key.

We use a left join so that every movie in the plot dataset is retained. This is important because plot summaries are a core component of the RAG pipeline, and we do not want to lose any plot records during the merge.

In [16]:
# Merge plots with metadata
combo_movies = movie_plots.merge(movies, on='wiki_movie_id', how='left')

# View result
combo_movies.head()

,wiki_movie_id,plot,freebase_movie_id,movie_name,release_date,bo_revenue,runtime,languages,countries,genres
0,23890098,"Shlykov, a hard-working taxi driver and Lyosha...",/m/076w2lb,Taxi Blues,1990-09-07,NaN,110.0,Russian,"France, Soviet Union, Russia","Drama, World cinema"
1,31186339,The nation of Panem consists of a wealthy Capi...,/m/0gkz15s,The Hunger Games,2012-03-12,686533290.0,142.0,English,United States of America,"Action/Adventure, Science Fiction, Action, Drama"
2,20663735,Poovalli Induchoodan is sentenced for six yea...,/m/051zjwb,Narasimham,2000,NaN,175.0,Malayalam,India,"Musical, Action, Drama, Bollywood"
3,2231378,"The Lemon Drop Kid , a New York City swindler,...",/m/06xtz3,The Lemon Drop Kid,1951-03-08,2300000.0,91.0,English,United States of America,"Screwball comedy, Comedy"
4,595909,Seventh-day Adventist Church pastor Michael Ch...,/m/02tqm5,A Cry in the Dark,1988-11-03,6908797.0,121.0,English,"United States of America, Australia, New Zealand","Crime Fiction, Drama, Docudrama, World cinema,..."

## Merging Character-Actor Data

Next, we merge the aggregated character-actor information into the combined movie dataset using `wiki_movie_id` as the key. This step adds each movie record with its corresponding cast information.

We again use a left join to ensure that all plots are retained, even if some do not have associated character-actor data.

In [17]:
# Merge character actor info on combined movie data
combo_movies = combo_movies.merge(characters_agg, on='wiki_movie_id', how='left')

# Print out shape
print(combo_movies.shape)

# View result
combo_movies.head()

(42303, 11)

,wiki_movie_id,plot,freebase_movie_id,movie_name,release_date,bo_revenue,runtime,languages,countries,genres,character_actor
0,23890098,"Shlykov, a hard-working taxi driver and Lyosha...",/m/076w2lb,Taxi Blues,1990-09-07,NaN,110.0,Russian,"France, Soviet Union, Russia","Drama, World cinema","Unknown Character: Natalia Koliakanova, Pyot..."
1,31186339,The nation of Panem consists of a wealthy Capi...,/m/0gkz15s,The Hunger Games,2012-03-12,686533290.0,142.0,English,United States of America,"Action/Adventure, Science Fiction, Action, Drama",Foxface: Jacqueline Emerson\nKatniss Everdeen...
2,20663735,Poovalli Induchoodan is sentenced for six yea...,/m/051zjwb,Narasimham,2000,NaN,175.0,Malayalam,India,"Musical, Action, Drama, Bollywood",M.K. Menon: Thilakan\nUnknown Character: Sai...
3,2231378,"The Lemon Drop Kid , a New York City swindler,...",/m/06xtz3,The Lemon Drop Kid,1951-03-08,2300000.0,91.0,English,United States of America,"Screwball comedy, Comedy","Unknown Character: Jane Darwell, Bob Hope, ..."
4,595909,Seventh-day Adventist Church pastor Michael Ch...,/m/02tqm5,A Cry in the Dark,1988-11-03,6908797.0,121.0,English,"United States of America, Australia, New Zealand","Crime Fiction, Drama, Docudrama, World cinema,...","Unknown Character: Frank Holden, Charles Dan..."

# Preprocessing

Since we already have one unique identifier for each movie we dropped ``freebase_movie_id``.

In [18]:
# Drop freebase_movie_id
combo_movies = combo_movies.drop(columns=['freebase_movie_id'])

# View result
combo_movies.head()

,wiki_movie_id,plot,movie_name,release_date,bo_revenue,runtime,languages,countries,genres,character_actor
0,23890098,"Shlykov, a hard-working taxi driver and Lyosha...",Taxi Blues,1990-09-07,NaN,110.0,Russian,"France, Soviet Union, Russia","Drama, World cinema","Unknown Character: Natalia Koliakanova, Pyot..."
1,31186339,The nation of Panem consists of a wealthy Capi...,The Hunger Games,2012-03-12,686533290.0,142.0,English,United States of America,"Action/Adventure, Science Fiction, Action, Drama",Foxface: Jacqueline Emerson\nKatniss Everdeen...
2,20663735,Poovalli Induchoodan is sentenced for six yea...,Narasimham,2000,NaN,175.0,Malayalam,India,"Musical, Action, Drama, Bollywood",M.K. Menon: Thilakan\nUnknown Character: Sai...
3,2231378,"The Lemon Drop Kid , a New York City swindler,...",The Lemon Drop Kid,1951-03-08,2300000.0,91.0,English,United States of America,"Screwball comedy, Comedy","Unknown Character: Jane Darwell, Bob Hope, ..."
4,595909,Seventh-day Adventist Church pastor Michael Ch...,A Cry in the Dark,1988-11-03,6908797.0,121.0,English,"United States of America, Australia, New Zealand","Crime Fiction, Drama, Docudrama, World cinema,...","Unknown Character: Frank Holden, Charles Dan..."

In [19]:
# View missing data
combo_movies.isnull().sum()

wiki_movie_id          0
plot                   0
movie_name            99
release_date        2717
bo_revenue         34716
runtime             6723
languages             99
countries             99
genres                99
character_actor     4524
dtype: int64

In [20]:
# Fill in missing data
combo_movies['movie_name'] = combo_movies['movie_name'].fillna("Unknown Movie")
combo_movies['release_date'] = combo_movies['release_date'].fillna("Unknown")
combo_movies['languages'] = combo_movies['languages'].fillna("Unknown")
combo_movies['countries'] = combo_movies['countries'].fillna("Unknown")
combo_movies['genres'] = combo_movies['genres'].fillna("Unknown")
combo_movies['character_actor'] = combo_movies['character_actor'].fillna("Unknown")

In [21]:
# Check dtypes
combo_movies.dtypes

wiki_movie_id        int64
plot                object
movie_name          object
release_date        object
bo_revenue         float64
runtime            float64
languages           object
countries           object
genres              object
character_actor     object
dtype: object

Below we convert numerical metadata columns to string because it fits with the RAG implementation better.

In [22]:
# Convert runtime and revenue to string and fill in missing values
for col in ['bo_revenue', 'runtime']:
    combo_movies[col] = combo_movies[col].astype(str)
    combo_movies[col] = combo_movies[col].fillna("Unknown")

In [23]:
# Remove leading/lagging white spaces in all text columns
for col in combo_movies.columns:
    if combo_movies[col].dtype == "object":
        combo_movies[col] = combo_movies[col].str.strip()

## Encoding Text Columns
Before continuing with preprocessing, we standardize text values across the dataset by applying a custom `encode_text()` function to all object-type columns.

This function checks whether a value is a string. If so, it encodes the text as UTF-8 and ignores any invalid characters before decoding it back into a clean string. We did this because we ran into some encoding errors and wanted to ensure that our encoding was standardized across all entries. 

**Reference:**
- https://www.geeksforgeeks.org/machine-learning/python-efficient-text-data-cleaning/

In [24]:
# Encode
def encode_text(text):
    """
    Clean a text value by enforcing UTF-8 encoding.

    This function checks whether the input is a string. If so, it encodes
    the text in UTF-8 while ignoring invalid characters, then decodes it
    back into a cleaned string. Non-string values are returned unchanged.

    Parameters
    -----------
        text : str 
            Input string to clean.

    Returns
    -------
        str
            UTF-8 cleaned string if the input is text, otherwise
            the original value.
    """
    # Ensure input is a string
    if type(text) == str:
        # Encode and decode
        cleaned_text = text.encode("utf-8", "ignore").decode("utf-8")
        return cleaned_text
    else:
        return text

In [25]:
# Iterate through columns
for col in combo_movies.columns:
    # Make sure dtype is object
    if combo_movies[col].dtype == "object":
        # Apply function
        combo_movies[col] = combo_movies[col].apply(encode_text)

## Plot Cleaning Function

We define a custom `clean_plot_text()` function to remove common formatting artifacts and markup from the raw movie plot summaries.

This function cleans raw movie plot text by:
- Decoding HTML entities
- Removing wiki templates and reference tags
- Stripping HTML and URLs
- Converting wiki links to readable text
- Normalizing whitespace

For a more detailed explanation of the regex patterns and cleaning steps, see `plot_cleaning_breakdown.md`.

In [ ]:
# Import regular expressions and html
import re
import html

# Define function for general plot cleaning
def clean_plot_text(text):
    """
    Clean raw movie plot text by decoding html, removing wiki templates,
    ref tags, and other unwanted text.

    This function is designed for plot summaries that contain wiki templates, 
    HTML tags, reference tags, URLs, wiki-style links, escaped characters, 
    and irregular whitespace. It applies a series of regex-based cleaning steps 
    to produce more readable and consistent text for downstream systems.

    Parameters
    ----------
        text : str
            Raw plot text

    Returns
    --------
        str or None
            Cleaned plot text, or None if the input is missing
            or becomes empty after cleaning.
    """
    # If plot is null
    if pd.isna(text):
        return None

    # Ensure plot is a string
    text = str(text)

    # Decode html entities
    text = html.unescape(text)

    # Remove common wiki templates ({{plot}}, {{tone}}, {{Expand section}}, {{long plot}})
    text = re.sub(r"\{\{[^{}]*\}\}", " ", text)

    # Remove ref tags like <ref>...</ref> and self-closing refs
    text = re.sub(r"<ref[^>]*>.*?</ref>", " ", text, flags=re.IGNORECASE | re.DOTALL)
    text = re.sub(r"<ref[^>]*/\s*>", " ", text, flags=re.IGNORECASE)

    # Remove other HTML tags
    text = re.sub(r"<[^>]+>", " ", text)

    # Remove URLs
    text = re.sub(r"http\S+|www\.\S+", " ", text)

    # Removes actors mentioned following a character
    text = re.sub(r"\(\[\[\s*[A-Z][a-z]+(?:[\s_]+[A-Z][a-z]+){0,3}(?:_+)?\s*,?", "", text) 
    
    # Convert wiki links
    text = re.sub(r"\[\[([^|\]]+)\|([^\]]+)\]\]", r"\2", text)
    text = re.sub(r"\[\[([^\]]+)\]\]", r"\1", text)

    # Remove leftover broken wiki brackets (just in case any where missed)
    text = text.replace("[[", " ").replace("]]", " ")

    # Fix common escaped characters
    text = text.replace("\\'", "'")
    
    # Normalize whitespace
    text = re.sub(r"\s+", " ", text).strip()
    
    # For empty strings
    if text == "":
        return None

    return text

In [27]:
# Apply to plot column
combo_movies['clean_plot'] = combo_movies['plot'].apply(clean_plot_text)

## Check Duplicates

In [28]:
# Check duplicates
combo_movies.duplicated().sum()

np.int64(0)

In [29]:
# Further inspect duplciates
combo_movies['movie_name'].duplicated().sum()

np.int64(2388)

### Handling Movies with the Same Title

While checking for duplicates in the movie dataset, we found that some movies share the same title. However these aren't cases of true duplicates, since some movies have remakes or reboots.

Because of this, we chose **not drop duplicate movie titles**. Instead, we will add a unique identifier such as: 
- **Wikipedia ID**
- **Movie Title**
- **Release Date**

to each chunk.

This should give the LLM enough information to differeniate between movies with identical names.

#### Example chunk format

```
Movie ID: 5875034
Movie Title: The Kingdom
Release Year: 2007-08-22

Plot Summary: ...
```

# Save Data
Lastly we save our clean merged movie dataset containing ``metadata``, ``character-actor information`` and ``plot summaries`` as a csv file.

In [30]:
# Save to csv file
combo_movies.to_csv("merged_movie_rag.csv",index=False, encoding="utf-8")